export const categoryFilters = [
  "All",
  "IELTS",
  "TOEIC",
  "Academic",
  "Business",
  "Daily",
  "Tech",
];

export const cefrFilters = ["All", "A1", "A2", "B1", "B2", "C1", "C2"];

export const topicFilters = [
  "All",
  "Writing",
  "Speaking",
  "Reading",
  "Work",
  "Travel",
  "Pronunciation",
  "Software",
  "Science",
];

export const catalogDecks = [
  {
    id: "ielts-band-7-lexis",
    title: "IELTS Band 7 Lexis",
    description:
      "Opinion, trend, education, and environment vocabulary with Vietnamese glosses.",
    level: "B2",
    wordCount: 680,
    categories: ["IELTS", "Academic"],
    topics: ["Writing", "Reading"],
    tags: ["essays", "collocations", "exam"],
    section: "popular",
    featured: true,
    tone: "azure",
  },
  {
    id: "toeic-workplace-core",
    title: "TOEIC Workplace Core",
    description:
      "Office, scheduling, purchasing, and business travel terms for TOEIC contexts.",
    level: "B1",
    wordCount: 540,
    categories: ["TOEIC", "Business"],
    topics: ["Work", "Travel"],
    tags: ["email", "meetings", "listening"],
    section: "popular",
    featured: true,
    tone: "cyan",
  },
  {
    id: "daily-english-foundation",
    title: "Daily English Foundation",
    description:
      "High-frequency phrases for routines, plans, preferences, and common responses.",
    level: "A2",
    wordCount: 420,
    categories: ["Daily"],
    topics: ["Speaking", "Travel"],
    tags: ["phrases", "routine", "fluency"],
    section: "popular",
    featured: false,
    tone: "mint",
  },
  {
    id: "academic-research-verbs",
    title: "Academic Research Verbs",
    description:
      "Precise verbs for papers, reports, citations, and research summaries.",
    level: "C1",
    wordCount: 360,
    categories: ["Academic"],
    topics: ["Writing", "Science"],
    tags: ["research", "reports", "formal"],
    section: "recommended",
    featured: false,
    tone: "sky",
  },
  {
    id: "business-negotiation",
    title: "Business Negotiation",
    description:
      "Vocabulary for proposals, tradeoffs, agreement, objections, and next steps.",
    level: "B2",
    wordCount: 310,
    categories: ["Business"],
    topics: ["Work", "Speaking"],
    tags: ["meetings", "strategy", "tone"],
    section: "popular",
    featured: false,
    tone: "violet",
  },
  {
    id: "tech-product-english",
    title: "Tech Product English",
    description:
      "Software, product, release, bug, analytics, and startup vocabulary.",
    level: "B2",
    wordCount: 390,
    categories: ["Tech", "Business"],
    topics: ["Software", "Work"],
    tags: ["software", "product", "teams"],
    section: "recommended",
    featured: true,
    tone: "azure",
  },
  {
    id: "pronunciation-minimal-pairs",
    title: "Pronunciation Minimal Pairs",
    description:
      "Common sound contrasts for Vietnamese speakers learning English pronunciation.",
    level: "B1",
    wordCount: 180,
    categories: ["Daily"],
    topics: ["Pronunciation", "Speaking"],
    tags: ["sounds", "listening", "speech"],
    section: "recommended",
    featured: false,
    tone: "cyan",
  },
  {
    id: "science-news-reader",
    title: "Science News Reader",
    description:
      "Climate, health, space, and technology terms for reading current reports.",
    level: "C1",
    wordCount: 450,
    categories: ["Academic", "Tech"],
    topics: ["Science", "Reading"],
    tags: ["news", "analysis", "context"],
    section: "recommended",
    featured: false,
    tone: "sky",
  },
];
