import type { Achievement, AchievementCategory } from "./types";

export const categoryFilters: AchievementCategory[] = [
  "All",
  "Streak",
  "XP",
  "Words",
  "Decks",
  "Accuracy",
  "Weak Words",
  "Pronunciation",
  "Hidden",
];

export const achievements: Achievement[] = [
  // ── Streak ──────────────────────────────────────────────────────────────
  {
    id: "streak-1",
    title: "First Steps",
    description: "Study for 3 consecutive days.",
    category: "Streak",
    state: "unlocked",
    tier: "bronze",
    xpReward: 50,
    unlockedAt: "2026-04-03",
    iconName: "Flame",
  },
  {
    id: "streak-2",
    title: "Week Warrior",
    description: "Maintain a 7-day study streak.",
    category: "Streak",
    state: "unlocked",
    tier: "silver",
    xpReward: 100,
    unlockedAt: "2026-04-28",
    iconName: "Flame",
  },
  {
    id: "streak-3",
    title: "Fortnight Focus",
    description: "Reach a 14-day study streak.",
    category: "Streak",
    state: "in_progress",
    tier: "silver",
    xpReward: 200,
    progress: 71,
    progressLabel: "10 / 14 days",
    iconName: "Flame",
  },
  {
    id: "streak-4",
    title: "Iron Discipline",
    description: "Hold a 30-day study streak without interruption.",
    category: "Streak",
    state: "locked",
    tier: "gold",
    xpReward: 500,
    iconName: "Flame",
  },
  {
    id: "streak-5",
    title: "Unbroken Chain",
    description: "Sustain a 60-day streak — the mark of a dedicated learner.",
    category: "Streak",
    state: "locked",
    tier: "platinum",
    xpReward: 1200,
    iconName: "Flame",
  },

  // ── XP ──────────────────────────────────────────────────────────────────
  {
    id: "xp-1",
    title: "First Spark",
    description: "Earn your first 100 XP.",
    category: "XP",
    state: "unlocked",
    tier: "bronze",
    xpReward: 30,
    unlockedAt: "2026-03-22",
    iconName: "Zap",
  },
  {
    id: "xp-2",
    title: "Rising Learner",
    description: "Accumulate 1,000 total XP.",
    category: "XP",
    state: "unlocked",
    tier: "silver",
    xpReward: 150,
    unlockedAt: "2026-05-06",
    iconName: "Zap",
  },
  {
    id: "xp-3",
    title: "Knowledge Seeker",
    description: "Earn a total of 5,000 XP across all sessions.",
    category: "XP",
    state: "in_progress",
    tier: "gold",
    xpReward: 400,
    progress: 76,
    progressLabel: "3,800 / 5,000 XP",
    iconName: "Zap",
  },
  {
    id: "xp-4",
    title: "Scholar",
    description: "Accumulate 25,000 XP — a true mark of dedication.",
    category: "XP",
    state: "locked",
    tier: "platinum",
    xpReward: 2000,
    iconName: "Zap",
  },

  // ── Words ────────────────────────────────────────────────────────────────
  {
    id: "words-1",
    title: "First Word",
    description: "Learn your very first English word.",
    category: "Words",
    state: "unlocked",
    tier: "bronze",
    xpReward: 10,
    unlockedAt: "2026-03-11",
    iconName: "BookOpen",
  },
  {
    id: "words-2",
    title: "Century",
    description: "Master 100 words in your deck library.",
    category: "Words",
    state: "unlocked",
    tier: "bronze",
    xpReward: 80,
    unlockedAt: "2026-04-15",
    iconName: "BookOpen",
  },
  {
    id: "words-3",
    title: "Vocabulary Builder",
    description: "Master 500 words across all installed decks.",
    category: "Words",
    state: "in_progress",
    tier: "silver",
    xpReward: 300,
    progress: 64,
    progressLabel: "320 / 500 words",
    iconName: "BookOpen",
  },
  {
    id: "words-4",
    title: "Word Master",
    description: "Reach 1,000 mastered words — full command of your material.",
    category: "Words",
    state: "locked",
    tier: "gold",
    xpReward: 750,
    iconName: "BookOpen",
  },

  // ── Decks ────────────────────────────────────────────────────────────────
  {
    id: "decks-1",
    title: "First Deck",
    description: "Install your first vocabulary deck.",
    category: "Decks",
    state: "unlocked",
    tier: "bronze",
    xpReward: 25,
    unlockedAt: "2026-03-11",
    iconName: "Layers",
  },
  {
    id: "decks-2",
    title: "Collector",
    description: "Own five installed decks in your library.",
    category: "Decks",
    state: "unlocked",
    tier: "silver",
    xpReward: 120,
    unlockedAt: "2026-05-10",
    iconName: "Layers",
  },
  {
    id: "decks-3",
    title: "Library Master",
    description: "Build a personal library of ten distinct decks.",
    category: "Decks",
    state: "locked",
    tier: "gold",
    xpReward: 350,
    iconName: "Layers",
  },

  // ── Accuracy ─────────────────────────────────────────────────────────────
  {
    id: "accuracy-1",
    title: "Sharp Eye",
    description: "Finish a review session with 90% or higher accuracy.",
    category: "Accuracy",
    state: "unlocked",
    tier: "silver",
    xpReward: 100,
    unlockedAt: "2026-05-14",
    iconName: "Target",
  },
  {
    id: "accuracy-2",
    title: "Flawless",
    description: "Achieve 100% accuracy in a complete review session.",
    category: "Accuracy",
    state: "locked",
    tier: "gold",
    xpReward: 400,
    iconName: "Target",
  },
  {
    id: "accuracy-3",
    title: "Consistent",
    description: "Maintain 85%+ accuracy across seven consecutive sessions.",
    category: "Accuracy",
    state: "in_progress",
    tier: "gold",
    xpReward: 600,
    progress: 71,
    progressLabel: "5 / 7 sessions",
    iconName: "Target",
  },

  // ── Weak Words ───────────────────────────────────────────────────────────
  {
    id: "weak-1",
    title: "Comeback",
    description: "Improve 10 words that were once in your weak list.",
    category: "Weak Words",
    state: "unlocked",
    tier: "bronze",
    xpReward: 75,
    unlockedAt: "2026-05-17",
    iconName: "TrendingUp",
  },
  {
    id: "weak-2",
    title: "Rehabilitated",
    description: "Clear every word from your weak word list.",
    category: "Weak Words",
    state: "locked",
    tier: "gold",
    xpReward: 500,
    iconName: "TrendingUp",
  },

  // ── Pronunciation ────────────────────────────────────────────────────────
  {
    id: "pron-1",
    title: "First Attempt",
    description: "Record your first pronunciation practice.",
    category: "Pronunciation",
    state: "unlocked",
    tier: "bronze",
    xpReward: 20,
    unlockedAt: "2026-02-28",
    iconName: "Mic",
  },
  {
    id: "pron-2",
    title: "Sound Check",
    description: "Complete 50 pronunciation practice recordings.",
    category: "Pronunciation",
    state: "in_progress",
    tier: "silver",
    xpReward: 200,
    progress: 64,
    progressLabel: "32 / 50 recordings",
    iconName: "Mic",
  },
  {
    id: "pron-3",
    title: "Clear Speech",
    description: "Achieve 95%+ accuracy in pronunciation evaluation.",
    category: "Pronunciation",
    state: "locked",
    tier: "gold",
    xpReward: 450,
    iconName: "Mic",
  },

  // ── Hidden ───────────────────────────────────────────────────────────────
  {
    id: "hidden-1",
    title: "Night Owl",
    description: "Study after midnight.",
    category: "Hidden",
    state: "hidden",
    tier: "silver",
    xpReward: 150,
    iconName: "Moon",
  },
  {
    id: "hidden-2",
    title: "Speed Run",
    description: "Complete a full session in under 5 minutes.",
    category: "Hidden",
    state: "hidden",
    tier: "gold",
    xpReward: 300,
    iconName: "Timer",
  },
  {
    id: "hidden-3",
    title: "Comeback Kid",
    description: "Return to studying after a 30-day absence.",
    category: "Hidden",
    state: "hidden",
    tier: "silver",
    xpReward: 250,
    iconName: "RotateCcw",
  },
];
